// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.EstablecerEquiposCopa(LigamaniaCoreApp.Models.ManagerViewModels.PreparacionTemporadaViewModel)~System.Threading.Tasks.Task{LigamaniaCoreApp.Utils.Response}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:No capture tipos de excepción generales.", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.EstablecerEquiposCopa(LigamaniaCoreApp.Models.ManagerViewModels.PreparacionTemporadaViewModel)~System.Threading.Tasks.Task{LigamaniaCoreApp.Utils.Response}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.SustituirEquipo(LigamaniaCoreApp.Models.ManagerViewModels.TemporadaEquipoAccion)~System.Threading.Tasks.Task{LigamaniaCoreApp.Utils.Response}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.SetRondasJornadasCopa(LigamaniaCoreApp.Data.DataModels.Base.Ligamania.Model.TemporadaDTO,LigamaniaCoreApp.Data.DataModels.Base.Ligamania.Model.TemporadaCompeticionDTO,System.Collections.Generic.List{LigamaniaCoreApp.Data.DataModels.Base.Ligamania.Model.CuadroCopaDTO},System.DateTime)~System.Threading.Tasks.Task{LigamaniaCoreApp.Utils.Response}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.FinalizarTemporada(System.Int32)~System.Threading.Tasks.Task{LigamaniaCoreApp.Utils.ResponseOfTReturn{LigamaniaCoreApp.Models.ManagerViewModels.TemporadaViewModel}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.GetTemporadaActual~System.Threading.Tasks.Task{LigamaniaCoreApp.Data.DataModels.Base.Ligamania.Model.TemporadaDTO}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.AgregarEquiposSupercopa(LigamaniaCoreApp.Models.ManagerViewModels.PreparacionTemporadaViewModel)~System.Threading.Tasks.Task{LigamaniaCoreApp.Utils.Response}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.AgregarEquipo(LigamaniaCoreApp.Models.ManagerViewModels.PreparacionTemporadaViewModel)~System.Threading.Tasks.Task{LigamaniaCoreApp.Utils.Response}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Especificar StringComparison", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.AgregarEquipo(LigamaniaCoreApp.Models.ManagerViewModels.PreparacionTemporadaViewModel)~System.Threading.Tasks.Task{LigamaniaCoreApp.Utils.Response}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.ActivarParaComenzarCompeticion(LigamaniaCoreApp.Models.ManagerViewModels.PreparacionTemporadaViewModel)~System.Threading.Tasks.Task{LigamaniaCoreApp.Utils.Response}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.GetTemporadaViewModelFinalizada~System.Threading.Tasks.Task{LigamaniaCoreApp.Models.ManagerViewModels.TemporadaViewModel}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.GetTemporadaViewModelActual~System.Threading.Tasks.Task{LigamaniaCoreApp.Models.ManagerViewModels.TemporadaViewModel}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:No pasar cadenas literal como parámetros localizados", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Services.ManagerService.GetTemporadaFinalizada~System.Threading.Tasks.Task{LigamaniaCoreApp.Data.DataModels.Base.Ligamania.Model.TemporadaDTO}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Las propiedades de colección deben ser de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~P:LigamaniaCoreApp.Data.DataModels.Base.Ligamania.Model.CompeticionDTO.TemporadaPartido")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Las propiedades de colección deben ser de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~P:LigamaniaCoreApp.Data.DataModels.Base.Ligamania.Model.ClubDTO.TemporadaJugador")]
[assembly: SuppressMessage("Design", "CA1054:Los parámetros de URI no deben ser cadenas", Justification = "<pendiente>", Scope = "member", Target = "~M:LigamaniaCoreApp.Controllers.AccountController.Login(LigamaniaCoreApp.Models.AccountViewModels.LoginViewModel,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
