using LigamaniaCoreApp.Data.DataModels.Base.Model;
using LigamaniaCoreApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LigamaniaCoreApp.Data.DataModels.Base.Ligamania.Model
{
    public partial class EquipoDTO : AuditableNameEntity
    {
        public EquipoDTO()
        {
            CambiosEquipoEquipoDestino = new HashSet<CambiosEquipoDTO>();
            CambiosEquipoEquipoOrigen = new HashSet<CambiosEquipoDTO>();
            TemporadaClasificacion = new HashSet<TemporadaClasificacionDTO>();
            TemporadaEquipo = new HashSet<TemporadaEquipoDTO>();
            TemporadaPartidoEquipoA = new HashSet<TemporadaPartidoDTO>();
            TemporadaPartidoEquipoB = new HashSet<TemporadaPartidoDTO>();
            TemporadaPartidoEquipoGanador = new HashSet<TemporadaPartidoDTO>();
        }

        public byte[] EscudoImage { get; set; }
        public bool Baja { get; set; }
        public int? Entrenador_Id { get; set; }
        public bool EsBot { get; set; }

        //Create foreign key with reference to ApplicationUser_Id that was auto-generated by entity framework.
        public virtual ApplicationUser ApplicationUser { get; set; }

        //[ForeignKey("Entrenador_Id")]
        //public virtual ApplicationUser Entrenador { get; set; }

        //public virtual Entrenador_DTO Entrenador { get; set; }
        public virtual ICollection<CambiosEquipoDTO> CambiosEquipoEquipoDestino { get; set; }
        public virtual ICollection<CambiosEquipoDTO> CambiosEquipoEquipoOrigen { get; set; }
        public virtual ICollection<TemporadaClasificacionDTO> TemporadaClasificacion { get; set; }
        public virtual ICollection<TemporadaEquipoDTO> TemporadaEquipo { get; set; }
        public virtual ICollection<TemporadaPartidoDTO> TemporadaPartidoEquipoA { get; set; }
        public virtual ICollection<TemporadaPartidoDTO> TemporadaPartidoEquipoB { get; set; }
        public virtual ICollection<TemporadaPartidoDTO> TemporadaPartidoEquipoGanador { get; set; }
    }
}
