//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PagosXml.Infraestructura;

using System.Text;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03", IsNullable=false)]
public partial class Document {
    
    private DocumentCstmrCdtTrfInitn cstmrCdtTrfInitnField;
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitn CstmrCdtTrfInitn {
        get {
            return this.cstmrCdtTrfInitnField;
        }
        set {
            this.cstmrCdtTrfInitnField = value;
        }
    }
    public Document() { cstmrCdtTrfInitnField = new DocumentCstmrCdtTrfInitn(); }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitn {
    
    private DocumentCstmrCdtTrfInitnGrpHdr grpHdrField;
    
    private DocumentCstmrCdtTrfInitnPmtInf pmtInfField;

    public DocumentCstmrCdtTrfInitn()
    {
        grpHdrField = new DocumentCstmrCdtTrfInitnGrpHdr();
        pmtInfField = new DocumentCstmrCdtTrfInitnPmtInf();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnGrpHdr GrpHdr {
        get {
            return this.grpHdrField;
        }
        set {
            this.grpHdrField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInf PmtInf {
        get {
            return this.pmtInfField;
        }
        set {
            this.pmtInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnGrpHdr {
    
    private string msgIdField;
    
    private System.DateTime creDtTmField;
    
    private sbyte nbOfTxsField;
    
    private DocumentCstmrCdtTrfInitnGrpHdrInitgPty initgPtyField;

    public DocumentCstmrCdtTrfInitnGrpHdr()
    {
        msgIdField = DateTime.Now.ToString("yyyyMMdd") + "OPA" + Utils.GetRandomString(13);
        creDtTmField = DateTime.Now;
        initgPtyField = new DocumentCstmrCdtTrfInitnGrpHdrInitgPty();
    }

    /// <remarks/>
    public string MsgId {
        get {
            return this.msgIdField;
        }
        set {
            this.msgIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
    
    /// <remarks/>
    public sbyte NbOfTxs {
        get {
            return this.nbOfTxsField;
        }
        set {
            this.nbOfTxsField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnGrpHdrInitgPty InitgPty {
        get {
            return this.initgPtyField;
        }
        set {
            this.initgPtyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnGrpHdrInitgPty {
    
    private string nmField;
    
    private DocumentCstmrCdtTrfInitnGrpHdrInitgPtyID idField;

    public DocumentCstmrCdtTrfInitnGrpHdrInitgPty()
    {
        idField = new DocumentCstmrCdtTrfInitnGrpHdrInitgPtyID();
    }

    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnGrpHdrInitgPtyID Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnGrpHdrInitgPtyID {
    
    private DocumentCstmrCdtTrfInitnGrpHdrInitgPtyIDOrgId orgIdField;

    public DocumentCstmrCdtTrfInitnGrpHdrInitgPtyID()
    {
        orgIdField = new DocumentCstmrCdtTrfInitnGrpHdrInitgPtyIDOrgId();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnGrpHdrInitgPtyIDOrgId OrgId {
        get {
            return this.orgIdField;
        }
        set {
            this.orgIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnGrpHdrInitgPtyIDOrgId {
    
    private DocumentCstmrCdtTrfInitnGrpHdrInitgPtyIDOrgIdOthr othrField;

    public DocumentCstmrCdtTrfInitnGrpHdrInitgPtyIDOrgId()
    {
        othrField = new DocumentCstmrCdtTrfInitnGrpHdrInitgPtyIDOrgIdOthr();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnGrpHdrInitgPtyIDOrgIdOthr Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnGrpHdrInitgPtyIDOrgIdOthr {
    
    private string idField;

    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInf {
    
    private string pmtInfIdField;
    
    private string pmtMtdField;
    
    private System.DateTime reqdExctnDtField;
    
    private DocumentCstmrCdtTrfInitnPmtInfDbtr dbtrField;
    
    private DocumentCstmrCdtTrfInitnPmtInfDbtrAcct dbtrAcctField;
    
    private DocumentCstmrCdtTrfInitnPmtInfDbtrAgt dbtrAgtField;
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInf[] cdtTrfTxInfField;

    public DocumentCstmrCdtTrfInitnPmtInf()
    {
        reqdExctnDtField = DateTime.Now;
        pmtInfIdField = DateTime.Now.ToString("yyyyMMdd") + "OPA" + Utils.GetRandomString(13);
        dbtrAcctField = new DocumentCstmrCdtTrfInitnPmtInfDbtrAcct();
        dbtrAgtField = new DocumentCstmrCdtTrfInitnPmtInfDbtrAgt();
        dbtrField = new DocumentCstmrCdtTrfInitnPmtInfDbtr();
    }

    /// <remarks/>
    public string PmtInfId {
        get {
            return this.pmtInfIdField;
        }
        set {
            this.pmtInfIdField = value;
        }
    }
    
    /// <remarks/>
    public string PmtMtd {
        get {
            return this.pmtMtdField;
        }
        set {
            this.pmtMtdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ReqdExctnDt {
        get {
            return this.reqdExctnDtField;
        }
        set {
            this.reqdExctnDtField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfDbtr Dbtr {
        get {
            return this.dbtrField;
        }
        set {
            this.dbtrField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfDbtrAcct DbtrAcct {
        get {
            return this.dbtrAcctField;
        }
        set {
            this.dbtrAcctField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfDbtrAgt DbtrAgt {
        get {
            return this.dbtrAgtField;
        }
        set {
            this.dbtrAgtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CdtTrfTxInf")]
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInf[] CdtTrfTxInf {
        get {
            return this.cdtTrfTxInfField;
        }
        set {
            this.cdtTrfTxInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfDbtr {
    
    private string nmField;
    
    private DocumentCstmrCdtTrfInitnPmtInfDbtrID idField;

    public DocumentCstmrCdtTrfInitnPmtInfDbtr()
    {
        idField = new DocumentCstmrCdtTrfInitnPmtInfDbtrID();
    }

    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfDbtrID Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfDbtrID {
    
    private DocumentCstmrCdtTrfInitnPmtInfDbtrIDOrgId orgIdField;

    public DocumentCstmrCdtTrfInitnPmtInfDbtrID()
    {
        orgIdField = new DocumentCstmrCdtTrfInitnPmtInfDbtrIDOrgId();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfDbtrIDOrgId OrgId {
        get {
            return this.orgIdField;
        }
        set {
            this.orgIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfDbtrIDOrgId {
    
    private DocumentCstmrCdtTrfInitnPmtInfDbtrIDOrgIdOthr othrField;

    public DocumentCstmrCdtTrfInitnPmtInfDbtrIDOrgId()
    {
        othrField = new DocumentCstmrCdtTrfInitnPmtInfDbtrIDOrgIdOthr();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfDbtrIDOrgIdOthr Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfDbtrIDOrgIdOthr {
    
    private string idField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfDbtrAcct {
    
    private DocumentCstmrCdtTrfInitnPmtInfDbtrAcctID idField;
    
    private string ccyField;

    public DocumentCstmrCdtTrfInitnPmtInfDbtrAcct()
    {
        idField = new DocumentCstmrCdtTrfInitnPmtInfDbtrAcctID();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfDbtrAcctID Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfDbtrAcctID {
    
    private string iBANField;
    
    /// <remarks/>
    public string IBAN {
        get {
            return this.iBANField;
        }
        set {
            this.iBANField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfDbtrAgt {
    
    private DocumentCstmrCdtTrfInitnPmtInfDbtrAgtFinInstnId finInstnIdField;

    public DocumentCstmrCdtTrfInitnPmtInfDbtrAgt()
    {
        finInstnIdField = new DocumentCstmrCdtTrfInitnPmtInfDbtrAgtFinInstnId();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfDbtrAgtFinInstnId FinInstnId {
        get {
            return this.finInstnIdField;
        }
        set {
            this.finInstnIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfDbtrAgtFinInstnId {
    
    private string bICField;
    
    /// <remarks/>
    public string BIC {
        get {
            return this.bICField;
        }
        set {
            this.bICField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInf {
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtId pmtIdField;
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtTpInf pmtTpInfField;
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmt amtField;
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtr cdtrField;
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcct cdtrAcctField;
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfRmtInf rmtInfField;

    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInf()
    {
        pmtIdField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtId();
        pmtTpInfField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtTpInf();
        amtField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmt();
        cdtrAcctField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcct();
        cdtrField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtr();
        rmtInfField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfRmtInf();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtId PmtId {
        get {
            return this.pmtIdField;
        }
        set {
            this.pmtIdField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtTpInf PmtTpInf {
        get {
            return this.pmtTpInfField;
        }
        set {
            this.pmtTpInfField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmt Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtr Cdtr {
        get {
            return this.cdtrField;
        }
        set {
            this.cdtrField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcct CdtrAcct {
        get {
            return this.cdtrAcctField;
        }
        set {
            this.cdtrAcctField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfRmtInf RmtInf {
        get {
            return this.rmtInfField;
        }
        set {
            this.rmtInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtId {
    
    private short endToEndIdField;
    
    /// <remarks/>
    public short EndToEndId {
        get {
            return this.endToEndIdField;
        }
        set {
            this.endToEndIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtTpInf {
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtTpInfSvcLvl svcLvlField;

    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtTpInf()
    {
        svcLvlField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtTpInfSvcLvl();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtTpInfSvcLvl SvcLvl {
        get {
            return this.svcLvlField;
        }
        set {
            this.svcLvlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtTpInfSvcLvl {
    
    private string cdField;
    
    /// <remarks/>
    public string Cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmt {
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmtInstdAmt instdAmtField;

    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmt()
    {
        instdAmtField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmtInstdAmt();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmtInstdAmt InstdAmt {
        get {
            return this.instdAmtField;
        }
        set {
            this.instdAmtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmtInstdAmt {
    
    private string ccyField;
    
    private float valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public float Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtr {
    
    private string nmField;
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrID idField;

    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtr()
    {
        idField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrID();
    }

    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrID Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrID {
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrIDPrvtId prvtIdField;

    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrID()
    {
        prvtIdField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrIDPrvtId();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrIDPrvtId PrvtId {
        get {
            return this.prvtIdField;
        }
        set {
            this.prvtIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrIDPrvtId {
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrIDPrvtIdOthr othrField;

    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrIDPrvtId()
    {
        othrField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrIDPrvtIdOthr();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrIDPrvtIdOthr Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrIDPrvtIdOthr {
    
    private string idField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcct {
    
    private DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcctID idField;

    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcct()
    {
        idField = new DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcctID();
    }

    /// <remarks/>
    public DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcctID Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcctID {
    
    private string iBANField;
    
    /// <remarks/>
    public string IBAN {
        get {
            return this.iBANField;
        }
        set {
            this.iBANField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03")]
public partial class DocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfRmtInf {
    
    private string ustrdField;
    
    /// <remarks/>
    public string Ustrd {
        get {
            return this.ustrdField;
        }
        set {
            this.ustrdField = value;
        }
    }
}
